### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by hissssst** [fannheyward/coc-terminal#34]
Toggling terminal two times causes the other buffer to become terminal too
![2019-12-05-120914_955x1048_scrot](https://user-images.githubusercontent.com/37012324/70220801-37443800-1758-11ea-9111-6b5487420320.png)

Then I receive this error when after toggling few times more ![2019-12-05-121153_945x1038_scrot](https://user-images.githubusercontent.com/37012324/70220995-87bb9580-1758-11ea-8af5-2c02fe110a88.png)

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

**Comment by matevskial** [comment]
Can confirm:
This is screen when I first toggle open the terminal:

![Screenshot_20200209_131812](https://user-images.githubusercontent.com/44746117/74101881-a1a19c00-4b3e-11ea-813f-be0d62165cb6.png)

This is screen when I toggle open the terminal for second time

![Screenshot_20200209_131859](https://user-images.githubusercontent.com/44746117/74101895-bda53d80-4b3e-11ea-97a6-f67d0af959d4.png)

And this is when I try to toggle close the terminal:

![Screenshot_20200209_132043](https://user-images.githubusercontent.com/44746117/74101923-fa713480-4b3e-11ea-8ba7-d7cbbe082202.png)

```
NVIM v0.3.8                                                                
Build type: Release
LuaJIT 2.1.0-beta3
```
