### ISSUE TITLE
Keybinding with <Plug>(coc-terminal-toggle) doesn't work, I have to use :CocCommand terminal.Toggle<CR>

### ISSUE THREAD

**Issue by matevskial** [fannheyward/coc-terminal#35]
**Configuration**
```
noremap <C-q> <Plug>(coc-terminal-toggle)
```
**Expected behavior**
To toggle the terminal

**Actual behavior**
Nothing

**Workaround**
```
noremap <C-q> :CocCommand terminal.Toggle<CR>
```

**Comment by fannheyward** [comment]
Try `nmap <C-q> <Plug>(coc-terminal-toggle)`

**Comment by rustiever** [comment]
above key is not working after running of command, for example if i toggle terminal then executing some commands like gcc/javac but after that i cannot toggle even if i press <ESC> key then toggle

**Comment by rustiever** [comment]
i found the solution
tnoremap <Esc> <C-\><C-n> will save you
for more info :help terminal
