### ISSUE TITLE
Terminal opens successfully, but there is no way to close it.

### ISSUE THREAD

**Issue by BrianZhang1** [fannheyward/coc-terminal#52]
In my .vimrc I have:
```
nmap <Leader>t <Plug>(coc-terminal-toggle)
tmap <Leader>t <Plug>(coc-terminal-toggle)
```
Terminal opens fine, but when I try to close it with \<Leader>t, this happens:
https://imgur.com/a/cjvTrAx 
I'm not sure how to exit the terminal, the only way I can do it is by closing my whole terminal that I am currently working in and reopening it, which is way too much of a hassle for me to use the plugin. Do you have any solution?

**Comment by mareksubocz** [comment]
Try:
```
tmap <Leader>t <C-\><C-n><Plug>(coc-terminal-toggle)
```
This will enter normal mode inside terminal first and then execute the command.

**Comment by BrianZhang1** [comment]
Ah, works like a charm! I tried your first solution before you edited it and it just froze and I was a little sad. I refreshed and your edit worked well! Thanks for being a lifesaver :)
