### ISSUE TITLE
Feature: Create configuration option for associating filetypes and REPL commands

### ISSUE THREAD

**Issue by lelutin** [fannheyward/coc-terminal#54]
Hello,

I just had an idea for this plugin but I unfortunately won't have the time to work on this soon. It would be nice if this plugin were using a configuration option for associating filetypes and their REPL instead of a hardcoded list. This would make it possible to override the currently set program names and would open the door for users to enable REPLs for more filetypes.

e.g. in coc-settings.json it could look something like this:

~~~
{
  "terminal.filetypes": {
    "python": "ipython3",
    "ruby": "irb"
  }
}
~~~

edit: fixed fenced code block syntax

**Comment by fannheyward** [comment]
Try `terminal.REPLMappings`.

**Comment by lelutin** [comment]
I tried setting this in a similar fashion than I described in the original message, but the same command "python" gets called instead of "ipython3".

Also when inputting this configuration in the `:CocConfig` interface, I received a message "[json] [W] Property terminal.REPLMappings is not allowed."

so I tried grepping for `REPLMappings` but I couldn't find any reference in any extension or in coc.nvim itself

**Comment by lelutin** [comment]
oh! sorry I was confused and I didn't see the commit you pushed. I will try this out now

**Comment by lelutin** [comment]
nice! it's working great. thanks that was really quick :100:
