### ISSUE TITLE
Enhancement: A config option to specify size of the terminal window as percentage of parent window height

### ISSUE THREAD

**Issue by poetaman** [fannheyward/coc-terminal#59]
Please add a config option to specify the size of terminal window as percentage of parent window height, with 100% being the full size of parent window where terminal was toggled from.

**Comment by fannheyward** [comment]
No, coc limited the size https://github.com/neoclide/coc.nvim/blob/2cece2600a433338074084e9cad3cac7ec4c3840/src/model/terminal.ts#L45. I suggest you use `resize 30` to resize the window.
