### ISSUE TITLE
Terminals are not destroyed on VimLeave

### ISSUE THREAD

**Issue by sainnhe** [fannheyward/coc-terminal#60]
The opened terminals are not destroyed in vim on VimLeave. When exit, an error occurs:

```
E947: Job still running in buffer "!/bin/zsh"
Press ENTER or type command to continue
```

I tried this autocmd, but still no luck:

```vim
autocmd VimLeave * CocCommand terminal.Destroy
```

Note that this bug doesn't exist in neovim.

**Comment by voler88** [comment]
This work:
autocmd QuitPre * CocCommand terminal.Destroy

**Comment by sainnhe** [comment]
> This work: autocmd QuitPre * CocCommand terminal.Destroy

It works! Thank you!
